<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>Recurly</PackageId>
    <Version>5.14.0</Version>
    <Authors>dx@recurly.com</Authors>
    <Company>Recurly, Inc.</Company>
    <Title>Recurly API Client</Title>
    <PackageDescription>The official .NET client for Recurly's V3 API.</PackageDescription>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="restsharp" Version="112.1.0" />
    <PackageReference Include="RestSharp.Serializers.NewtonsoftJson" Version="112.1.0" />
  </ItemGroup>
</Project>
